osx_image: xcode11.5
language: objective-c
podfile: TestLeoVegas/Podfile

before_install:
    - gem install cocoapods
    - gem update concurrent-ruby
    - pod setup

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace TestLeoVegas/TestLeoVegas.xcworkspace -scheme TestLeoVegas -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

